default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: scripta
  password: Dfr368qE
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: ScriptaNew_development

test:
  <<: *default
  database: ScriptaNew_test

production:
  <<: *default
  database: ScriptaNew_production
  username: Scripta
  password: <%= ENV['SCRIPTA_DATABASE_PASSWORD'] %>
